# This file is used to run integration tests on travis
version: '3'
services:

  dashboard:
      build: .
      ports:
        - "8082:8082"
      environment: 
        REACT_APP_JANUS_URI: http://gw.staging.hellofresh.io:8081 
        REACT_APP_CLIENT_ID: 07d212d657ed8f988287
        REACT_APP_SCOPE: read:org
        REACT_APP_GITHUB_TOKEN_URL: https://gw-staging.hellofresh.com/auth/github/token
        REACT_APP_JANUS_TOKEN_URL: http://gw.staging.hellofresh.io:8081
        REACT_APP_GITHUB_AUTHORIZE_URL: https://gw-staging.hellofresh.com/auth/github/authorize
