# This file is used to run integration tests on travis
version: '3'
services:

  dashboard:
      build: .
      ports:
        - "8082:8082"
      environment: 
        REACT_APP_JANUS_URI: http://localhost:8081 
        REACT_APP_CLIENT_ID: yourClientID
        REACT_APP_SCOPE: read:org
        REACT_APP_GITHUB_TOKEN_URL:  http://localhost:8080/auth/github/token
        REACT_APP_JANUS_TOKEN_URL: http://localhost:8081
        REACT_APP_GITHUB_AUTHORIZE_URL: http://localhost:8080/auth/github/authorize
