name: Release

on:
  release:
    types:
      - created

jobs:
  docker:
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image and push to the registry
        uses: docker/build-push-action@v1
        with:
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          repository: "hellofreshtech/janus-dashboard"
          username: hellofreshtech
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          tags: latest
